# Generated by Django 3.2.9 on 2022-03-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ACCOUNTS', '0002_employee_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Productie', 'Productie'), ('Mentenanta', 'Mentenanta'), ('Admin', 'Admin')], max_length=100),
        ),
    ]
