# Generated by Django 3.2.9 on 2022-03-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ACCOUNTS', '0003_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Zona',
            field=models.CharField(choices=[('Asamblare', 'Asamblare'), ('Airbag', 'Airbag'), ('Foaming', 'Foaming'), ('Diecasting', 'Diecasting'), ('LW', 'LW'), ('IMO', 'IMO'), ('Toolshop', 'Toolshop')], max_length=100),
        ),
    ]
