# Generated by Django 3.2.9 on 2021-12-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ASSETS', '0002_raportavarieasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asset_Raport', to='GAIA_ASSETS.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Cod_Marca_MAINT',
            field=models.IntegerField(default=0, verbose_name='Cod Marca Tehnician Mentenanta'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Cod_Marca_ME_1',
            field=models.IntegerField(default=0, verbose_name='Cod Marca Initiator Raport Avarie'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Cod_Marca_ME_2',
            field=models.IntegerField(default=0, verbose_name='Cod Marca Persoanei Aprobare Inchidere Avarie'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Comunicat_la_intretinere',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Comunicare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_finalizata',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Finalizare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_inceputa',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Preluare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='NUME_MAINT',
            field=models.CharField(default='empty', max_length=80, verbose_name='Nume Tehnician Mentenanta'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='NUME_ME_1',
            field=models.CharField(default='empty', max_length=80, verbose_name='Nume Initiator Raport Avarie'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='NUME_ME_2',
            field=models.CharField(default='empty', max_length=80, verbose_name='Numele Persoanei Aprobare Inchidere Avarie'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Observatii',
            field=models.CharField(default='empty', max_length=80, verbose_name='Observatii'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Semnalat_de_productie',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Semnalare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Status',
            field=models.BooleanField(verbose_name='Status INCHIS/DESCHIS'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Status_OPEN',
            field=models.BooleanField(verbose_name='Status ME/MNT'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='activitati_efectuate',
            field=models.CharField(default='empty', max_length=80, verbose_name='Activitati Efectuate'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='cauza_avariei',
            field=models.CharField(default='empty', max_length=80, verbose_name='Cauza Avariei'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='denumire',
            field=models.CharField(default='empty', max_length=50, verbose_name='Denumirea Raportului'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='descriere',
            field=models.CharField(default='empty', max_length=80, verbose_name='Descrierea Raportului'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='durata_interventie',
            field=models.TimeField(default='0:00', verbose_name='Durata Interventie'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='numar',
            field=models.IntegerField(default=0, verbose_name='Numarul Raportului'),
        ),
    ]
