# Generated by Django 3.2.9 on 2021-12-04 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ASSETS', '0004_auto_20211204_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Comunicat_la_intretinere',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 14, 10, 48, 563343), verbose_name='Data Comunicare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_finalizata',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 14, 10, 48, 563343), verbose_name='Data Finalizare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_inceputa',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 14, 10, 48, 563343), verbose_name='Data Preluare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Semnalat_de_productie',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 14, 10, 48, 563343), verbose_name='Data Semnalare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='durata_interventie',
            field=models.TimeField(verbose_name='Durata Interventie'),
        ),
    ]
