# Generated by Django 3.2.9 on 2021-12-06 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ASSETS', '0006_auto_20211206_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportavarieasset',
            name='Status_Preluat_MNT',
            field=models.BooleanField(default=0, verbose_name='Preluat NE/Preluat'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Comunicat_la_intretinere',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 14, 6, 40, 878826), verbose_name='Data Comunicare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_finalizata',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 14, 6, 40, 878826), verbose_name='Data Finalizare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_inceputa',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 14, 6, 40, 878826), verbose_name='Data Preluare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Semnalat_de_productie',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 14, 6, 40, 878826), verbose_name='Data Semnalare Raport'),
        ),
    ]
