# Generated by Django 3.2.9 on 2021-12-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ASSETS', '0009_auto_20211210_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avarieasset',
            name='denumire',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='RaportAvarieAsset',
        ),
    ]
