# Generated by Django 3.2.9 on 2022-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ASSETS', '0010_auto_20211215_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasset',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
