# Generated by Django 3.2.9 on 2022-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiune',
            name='status',
            field=models.CharField(choices=[('I', 'Actiune nefinalizata la timp'), ('O', 'Actiune in desfasurar'), ('C', 'Actiune incheiata'), ('E', 'Actiune incheiata eficace')], max_length=1),
        ),
    ]
