# Generated by Django 3.2.9 on 2022-02-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0002_alter_actiune_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiune',
            name='data_deschidre_actiune',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='actiune',
            name='data_finaliarii',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='actiune',
            name='data_preconizare_finalizare',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='actiune',
            name='data_verificarii_eficientei',
            field=models.CharField(max_length=10),
        ),
    ]
