# Generated by Django 3.2.9 on 2022-02-25 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0003_auto_20220225_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiune',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 15, 31, 6, 72002)),
        ),
    ]
