# Generated by Django 3.2.9 on 2022-02-28 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0005_auto_20220225_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiune',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 28, 11, 13, 41, 198173)),
        ),
        migrations.AlterField(
            model_name='actiune',
            name='status',
            field=models.CharField(choices=[('I', 'Actiune nefinalizata la timp'), ('O', 'Actiune in desfasurare'), ('C', 'Actiune incheiata'), ('E', 'Actiune incheiata eficace')], max_length=1),
        ),
    ]
