# Generated by Django 3.2.9 on 2022-03-02 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0006_auto_20220228_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiune',
            options={'ordering': ['-hide_date']},
        ),
        migrations.AlterField(
            model_name='actiune',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 12, 12, 41, 294688)),
        ),
    ]
