# Generated by Django 3.2.9 on 2022-03-16 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0007_auto_20220302_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiune',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 16, 12, 38, 6, 172702)),
        ),
    ]
