# Generated by Django 3.2.9 on 2022-03-16 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0009_alter_actiune_hide_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiune',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 16, 12, 45, 31, 219412)),
        ),
    ]
