# Generated by Django 3.2.9 on 2022-03-24 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0010_alter_actiune_hide_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiune',
            name='data_finaliarii',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='actiune',
            name='data_verificarii_eficientei',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='actiune',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 14, 41, 52, 509883)),
        ),
    ]
