# Generated by Django 4.0.4 on 2022-04-18 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_PLAN_ACTIUNI', '0011_auto_20220324_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiune',
            name='hide_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 18, 20, 0, 38, 62990)),
        ),
    ]
