# Generated by Django 3.2.9 on 2022-02-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=70, unique=True)),
                ('part_no', models.CharField(max_length=70, unique=True)),
                ('stock_qty', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('minimun_stock_qty', models.IntegerField()),
                ('maximum_stock_qty', models.IntegerField()),
                ('critical', models.BooleanField()),
                ('locatiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GAIA_MAGAZIE.location')),
            ],
        ),
    ]
