# Generated by Django 3.2.9 on 2022-02-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_MAGAZIE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='locatiom',
            new_name='location',
        ),
    ]
