# Generated by Django 3.2.9 on 2022-02-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_MAGAZIE', '0002_rename_locatiom_item_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['nume']},
        ),
    ]
