# Generated by Django 3.2.9 on 2021-12-15 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GAIA_ASSETS', '0010_auto_20211215_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaportAvarieAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.IntegerField(default=0, verbose_name='Numarul Raportului')),
                ('denumire', models.CharField(default='empty', max_length=50, verbose_name='Denumirea Raportului')),
                ('descriere', models.CharField(default='empty', max_length=80, verbose_name='Descrierea Raportului')),
                ('activitati_efectuate', models.CharField(default='empty', max_length=80, verbose_name='Activitati Efectuate')),
                ('Status', models.BooleanField(verbose_name='Status INCHIS/DESCHIS')),
                ('Status_OPEN', models.BooleanField(verbose_name='Status ME/MNT')),
                ('Status_Preluat_MNT', models.BooleanField(default=0, verbose_name='Preluat NE/Preluat')),
                ('Observatii', models.CharField(default='empty', max_length=80, verbose_name='Observatii')),
                ('NUME_MAINT', models.CharField(default='empty', max_length=80, verbose_name='Nume Tehnician Mentenanta')),
                ('Cod_Marca_MAINT', models.IntegerField(default=0, verbose_name='Cod Marca Tehnician Mentenanta')),
                ('NUME_ME_1', models.CharField(default='empty', max_length=80, verbose_name='Nume Initiator Raport Avarie')),
                ('Cod_Marca_ME_1', models.IntegerField(default=0, verbose_name='Cod Marca Initiator Raport Avarie')),
                ('NUME_ME_2', models.CharField(default='empty', max_length=80, verbose_name='Numele Persoanei Aprobare Inchidere Avarie')),
                ('Cod_Marca_ME_2', models.IntegerField(default=0, verbose_name='Cod Marca Persoanei Aprobare Inchidere Avarie')),
                ('Semnalat_de_productie', models.DateTimeField(default=datetime.datetime(2021, 12, 15, 8, 43, 41, 588200), verbose_name='Data Semnalare Raport')),
                ('Comunicat_la_intretinere', models.DateTimeField(default=datetime.datetime(2021, 12, 15, 8, 43, 41, 588200), verbose_name='Data Comunicare Raport')),
                ('Interventie_inceputa', models.DateTimeField(default=datetime.datetime(2021, 12, 15, 8, 43, 41, 588200), verbose_name='Data Preluare Raport')),
                ('Interventie_finalizata', models.DateTimeField(default=datetime.datetime(2021, 12, 15, 8, 43, 41, 588200), verbose_name='Data Finalizare Raport')),
                ('durata_interventie', models.IntegerField(default=0, verbose_name='Durata Interventie')),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asset_Raport', to='GAIA_ASSETS.asset', verbose_name='Asset')),
                ('cauza_avariei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Avarie_raport', to='GAIA_ASSETS.asset')),
            ],
        ),
    ]
