# Generated by Django 3.2.9 on 2021-12-21 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ASSETS', '0010_auto_20211215_0843'),
        ('GAIA_ME_CORECTIVA', '0003_auto_20211215_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Comunicat_la_intretinere',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 452731), verbose_name='Data Comunicare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_finalizata',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 452731), verbose_name='Data Finalizare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_inceputa',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 452731), verbose_name='Data Preluare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Semnalat_de_productie',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 452731), verbose_name='Data Semnalare Raport'),
        ),
        migrations.CreateModel(
            name='RaportAvarieSubAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.IntegerField(default=0, verbose_name='Numarul Raportului')),
                ('denumire', models.CharField(default='empty', max_length=50, verbose_name='Denumirea Raportului')),
                ('descriere', models.CharField(default='empty', max_length=80, verbose_name='Descrierea Raportului')),
                ('activitati_efectuate', models.CharField(default='empty', max_length=80, verbose_name='Activitati Efectuate')),
                ('Status', models.BooleanField(verbose_name='Status INCHIS/DESCHIS')),
                ('Status_OPEN', models.BooleanField(verbose_name='Status ME/MNT')),
                ('Status_Preluat_MNT', models.BooleanField(default=0, verbose_name='Preluat NE/Preluat')),
                ('Observatii', models.CharField(default='empty', max_length=80, verbose_name='Observatii')),
                ('NUME_MAINT', models.CharField(default='empty', max_length=80, verbose_name='Nume Tehnician Mentenanta')),
                ('Cod_Marca_MAINT', models.IntegerField(default=0, verbose_name='Cod Marca Tehnician Mentenanta')),
                ('NUME_ME_1', models.CharField(default='empty', max_length=80, verbose_name='Nume Initiator Raport Avarie')),
                ('Cod_Marca_ME_1', models.IntegerField(default=0, verbose_name='Cod Marca Initiator Raport Avarie')),
                ('NUME_ME_2', models.CharField(default='empty', max_length=80, verbose_name='Numele Persoanei Aprobare Inchidere Avarie')),
                ('Cod_Marca_ME_2', models.IntegerField(default=0, verbose_name='Cod Marca Persoanei Aprobare Inchidere Avarie')),
                ('Semnalat_de_productie', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 453756), verbose_name='Data Semnalare Raport')),
                ('Comunicat_la_intretinere', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 453756), verbose_name='Data Comunicare Raport')),
                ('Interventie_inceputa', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 453756), verbose_name='Data Preluare Raport')),
                ('Interventie_finalizata', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 10, 59, 453756), verbose_name='Data Finalizare Raport')),
                ('durata_interventie', models.IntegerField(default=0, verbose_name='Durata Interventie')),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asset_Raport_Sub', to='GAIA_ASSETS.asset', verbose_name='Asset_Sub')),
                ('SubAsset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Asset_Raport_Sub', to='GAIA_ASSETS.subasset', verbose_name='SubAsset_Sub')),
                ('cauza_avariei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avarie_raport_Sub', to='GAIA_ASSETS.avarieasset')),
            ],
        ),
    ]
