# Generated by Django 3.2.9 on 2022-01-10 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAIA_ME_CORECTIVA', '0004_auto_20211221_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Comunicat_la_intretinere',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 626371), verbose_name='Data Comunicare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_finalizata',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 626371), verbose_name='Data Finalizare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Interventie_inceputa',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 626371), verbose_name='Data Preluare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavarieasset',
            name='Semnalat_de_productie',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 626371), verbose_name='Data Semnalare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavariesubasset',
            name='Comunicat_la_intretinere',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 627368), verbose_name='Data Comunicare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavariesubasset',
            name='Interventie_finalizata',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 627368), verbose_name='Data Finalizare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavariesubasset',
            name='Interventie_inceputa',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 627368), verbose_name='Data Preluare Raport'),
        ),
        migrations.AlterField(
            model_name='raportavariesubasset',
            name='Semnalat_de_productie',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 14, 35, 41, 627368), verbose_name='Data Semnalare Raport'),
        ),
    ]
